### ISSUE TITLE
Problem with placing stars in the NIRISS field.

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/mirage#196]
I have run a set of 35 mirage simulations to make the scene images.  These are a set of proposed NIRISS commissioning fields.  All the files and mirage outputs are found at /ifs/jwst/wit/niriss/kevin/cars_simulations/ with files such as niriss_field01_F356W_combined.yaml.  Each field has a specific position and rotation.  The positions are listed in pos1.out.  The rotations can be seen in the targets.xlsx file.

The first few fields look OK, but field07 for example shows a narrow strip of stars across the field.  The image below shows the scene seed image.  One sees that the stars are not distributed over the entire detector.  The nominal position is 00h47m04.4540s +85d16m32.70s.

![field07_combined_image](https://user-images.githubusercontent.com/37000208/47314499-db7c2580-d60f-11e8-9de8-264eab31adf7.gif)

I checked the original source list, and the next plot shows the sky positions plus the expected projection of the NIRISS field of view on the sky in this orientation.  The black circles show all the targets on the original input source list.  The red diamonds show the ones that are listed in the field07_combined_F356W_uncal_pointsources.list output file from the mirage run for the input star list.

![field07](https://user-images.githubusercontent.com/37000208/47314514-e59e2400-d60f-11e8-9395-fd4c4b3957e4.gif)

The strip of stars that is selected is the same for rotation 200 degrees shown just above, for rotation 0 degrees, and for rotation 90 degrees, which seems a little odd to me.  It looks like something is wrong in converting the star list from decimal degrees into pixels, and that this is not affected by the rotation that is selected.  I verified that the bright source at the top of the scene image is the red diamond at the bottom of the detector as seen in the above Figure, so I think the orientation in the Figure is correct and corresponds to the scene image. 

One might speculate that the cosine (declination) factor is wrong or missing in the conversion from sky position to pixels, so the strip of stars in the example is narrow because the range of RA in degrees gets magnified as one goes to the poles in the equatorial coordinates.  However all this should be taken care of properly in the code.  I see nothing in the code that suggests that such an error has been made.

The really odd thing to me is that the first position (15h59m37.5300s -20d33m42.24s) seems to produce an output field image that looks like the Aladin view of the sky position.  Of course, the cosine term is about 0.86 at that declination so maybe the issue is there but I cannot see it by eye.

In any case, there is a problem here that needs to be looked at.  It seems to me that the code is doing the conversion correctly via RADectoXY_astrometric but still it is not working in the case above and a few others out of the 35 fields.

**Comment by bhilbert4** [comment]
Strange. My first thought is that this looks like a problem I was having last week where I was getting an inconsistent number of sources in the fov (with some that were inappropriately appearing/disappearing) between dithers. But that issue turned out to be because I was using a branch of Mirage that was not filtering out sources very far from the detector, and it just so happened that the distortion model very far (~10 detector widths) was placing these sources onto the detector when converting from RA, Dec to x,y. 

Anyway, I can have a look if you want me to. Just send me the source catalog and yaml file for field07.

**Comment by bhilbert4** [comment]
<img width="830" alt="temp" src="https://user-images.githubusercontent.com/11775426/47316809-f6519880-d615-11e8-9dc0-e6fd5c01ddbb.png">

When I try running the field07 files, I get 79 point sources on the detector, and the coverage looks pretty reasonable.

**Comment by bhilbert4** [comment]
Maybe your master branch is out of date somehow? I'm not sure what code changes would result in the output you're getting though.

**Comment by KevinVolkSTScI** [comment]
OK thank you for testing it, Bryan.  The branch I am running for this test is a bit out of date because it has the PSF library and I wanted to "freeze" the code version before the changes to the new PSF file.  I have a more recent version (should be up to date) installed as well so I will try that.
I am concerned that the issue is outside mirage somehow, and might be difficult to track down.  I think the code for the (RA,Dec) -> (pixel x, pixel y) has not changed recently, hence the concern about something outside mirage proper changing.

**Comment by bhilbert4** [comment]
As long as you are providing a distortion reference file, I don't think the translation from RA, Dec to x,y should not have changed. The model coefficients are all contained within the reference file. The only way that things could change (and this happened to NIRCam recently) is if the information in pysiaf does not agree with the information in the distortion reference file. That's because v2_ref and v3_ref come from pysiaf and are used to build the attitude matrix, but the distortion coefficients come from the reference file. So an inconsistency will show up as a problem with the WCS. But in NIRCam's case, a small shift in v2_ref, v3_ref and model coefficients made for only a very small (incorrect) rotation. I think it would take a large difference between pysiaf and the reference file to have any kind of effect like you're seeing.

**Comment by KevinVolkSTScI** [comment]
I do not have any idea why this happened, but switching to a different conda environment and mirage installation appears to have fixed the problem.  Hence I am closing this issue.
