### ISSUE TITLE
Update catalog input to include galaxy/extended catalogs

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/mirage#213]
I might be missing something, but it seems to be like the elegant new way to pass catalogs into MIRAGE using a dictionary (implemented in #172) is restricted to the point source catalogs.

It seems logical to, eventually, extend that structure for catalogs of galaxies and extended sources.

**Comment by bhilbert4** [comment]
Suggestion from @NorPirzkal that seems like a good idea:
Re-work the catalog inputs to be per APT Fixed Target, rather than per Observation. This cuts down on repeats.

For example, in a proposal with 2 targets ("Targ1", and "Targ2") and 10 observations:
catalogs = {‘Targ1’: {‘pointsource':[catalog_p1.cat]},{‘galaxies':[catalog_g1.cat]}, 'Targ2’: {'pointsource':[catalog_p2.cat], 'galaxies': [catalog_g2.cat]}}

Note that we would need to either add an additional layer for instrument, or assume that magnitudes for all instruments are in the catalog files. Do we also assume that SW and LW filter magnitudes are combined in the catalogs?

rather than:

catalogs = {‘nircam’: {‘sw’: [cat1.txt, cat1.txt, cat2.txt, cat1.txt, cat1.txt, cat2.txt, cat1.txt, cat1.txt, cat2.txt, cat1.txt], ‘lw’: [lw_cat1.txt, lw_cat1.txt, lw_cat2.txt, lw_cat1.txt, lw_cat1.txt, lw_cat2.txt, lw_cat1.txt, lw_cat1.txt, lw_cat2.txt, lw_cat1.txt]}}
where the list of catalogs is assumed to match up to the list of observations.
